/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'stencil-popup';


export namespace Components {

  interface StencilSocialAuth {
    'config': object;
    'dev': boolean;
    'getToken': () => Promise<string>;
    'isAuthenticated': () => Promise<boolean>;
    'provider': string;
    'removeToken': () => Promise<boolean>;
  }
  interface StencilSocialAuthAttributes extends StencilHTMLAttributes {
    'config'?: object;
    'dev'?: boolean;
    'onAuthResponse'?: (event: CustomEvent) => void;
    'provider'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StencilSocialAuth': Components.StencilSocialAuth;
  }

  interface StencilIntrinsicElements {
    'stencil-social-auth': Components.StencilSocialAuthAttributes;
  }


  interface HTMLStencilSocialAuthElement extends Components.StencilSocialAuth, HTMLStencilElement {}
  var HTMLStencilSocialAuthElement: {
    prototype: HTMLStencilSocialAuthElement;
    new (): HTMLStencilSocialAuthElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-social-auth': HTMLStencilSocialAuthElement
  }

  interface ElementTagNameMap {
    'stencil-social-auth': HTMLStencilSocialAuthElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
